import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './ui/globals.css'
import { cn } from '@/lib/utils';
import React from "react";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {
    children: React.ReactNode,
}) {
  return (
    <html lang="en">
      <body className={cn(
        inter.className,
        'bg-[#c5ecf0]'
      )}>{children}</body>
    </html>
  )
}
